import type { VehicleType } from "./types";

/**
 * Sweep completo del catalogo, marca per marca: dalle nuove entrate (EV cinesi, startup) alle
 * vecchie glorie (marchi storici, modelli d'epoca e da competizione). Solo nomi di modello:
 * niente motorizzazioni, quindi il form ricade sul campo libero come per CATALOGUE_EXTENSIONS.
 * Scritto a mano da conoscenza generale, nessuno scraping e nessuna ricerca IA a runtime.
 * I duplicati con gli altri dataset sono innocui: getModels() deduplica.
 */
export const CATALOGUE_SWEEP: Record<VehicleType, Record<string, string[]>> = {
  auto: {
    // ---------- Marchi gia' presenti: ampliamento gamma ----------
    Abarth: ["600e", "750", "850 TC", "1000 TC", "131 Rally", "2000 Sport", "OT 1300", "Ritmo 130 TC", "Simca 1300"],
    AIXAM: ["500", "A741", "Crossline", "Crossover", "D-Truck", "e-City", "e-Coupé", "Scouty"],
    "Alfa Romeo": ["1750", "2000", "6C", "8C 2900", "156 Crosswagon", "Disco Volante", "Duetto", "Giulia GT", "Giulia GTA", "Giulia TZ", "Giulietta Sprint", "Junior Zagato", "Matta", "Milano", "P2", "P3", "Tipo 33"],
    Alpine: ["A210", "A220", "A290", "A390"],
    "Aston Martin": ["Bulldog", "Cygnet", "DB AR1", "DB2", "DB2/4", "DB3", "DB10", "DBS", "Lagonda Taraf", "Rapide", "V8", "Valour", "Vanquish", "Victor", "Vulcan"],
    Audi: ["60", "75", "4000", "5000", "allroad", "Cabriolet", "e-tron", "F103", "RS2", "S2", "Super 90"],
    Autobianchi: ["A111", "Bianchina Eden Roc", "Bianchina Giardiniera", "Bianchina Panoramica"],
    BAIC: ["Beijing U5 Plus", "Beijing X7", "BJ30", "BJ80", "D50", "EU5", "EU7", "Senova"],
    Bentley: ["3 Litre", "4½ Litre", "8 Litre", "Bacalar", "Batur", "Continental GT", "Continental GTC", "Continental R", "Continental T", "Corniche", "Mark VI", "S1", "S2", "S3", "Speed Six", "T-Series"],
    BMW: ["3/15", "328", "501", "502", "503", "600", "700", "1600", "1602", "1800", "2000 CS", "3200 CS", "M Coupé", "M Roadster", "M6", "Serie 2 Gran Tourer", "Serie 3 Gran Turismo", "Serie 5 Gran Turismo"],
    BYD: ["Destroyer 05", "e2", "e3", "e6", "F0", "F3", "F6", "Frigate 07", "G3", "M6", "Qin", "Qin Plus", "S6", "Seal 6", "Shark 6", "Song", "Song Plus", "Song Pro", "Yuan Pro"],
    Cadillac: ["Allanté", "BLS", "Brougham", "Catera", "Celestiq", "CT6", "DTS", "Escalade IQ", "Fleetwood", "Optiq", "Series 62", "STS", "Vistiq", "XLR"],
    Casalini: ["Kerry", "M10", "M12", "M14", "Sulky", "Ydea"],
    Chatenet: ["Barooder", "CH28", "CH30", "CH32", "CH40", "Media", "Speedino"],
    Chevrolet: ["Astro", "Bel Air", "Beretta", "C10", "Cavalier", "Chevette", "Cobalt", "Colorado", "Corvair", "El Camino", "Equinox", "Evanda", "HHR", "Lacetti", "Lumina", "Monte Carlo", "Nubira", "Rezzo", "Silverado", "Sonic", "SSR", "Suburban", "Traverse", "Uplander", "Venture"],
    Chrysler: ["180", "Airflow", "Aspen", "Cordoba", "Imperial", "LeBaron", "New Yorker", "Pacifica", "Prowler", "Saratoga", "Vision"],
    Citroën: ["Acadiane", "Ami 6", "Ami 8", "Basalt", "Bijou", "C25", "C35", "C3L", "C4 SpaceTourer", "CX", "ë-C3", "ë-C4", "Grand C4 Picasso", "Grand C4 SpaceTourer", "HY", "LNA"],
    Dacia: ["1300", "1310", "1410", "Logan MCV", "Nova", "Pick-Up", "Solenza", "SuperNova"],
    Daewoo: ["Chairman", "Cielo", "Damas", "Evanda", "Kalos", "Korando", "Labo", "Musso", "Nexia", "Prince", "Racer", "Rezzo"],
    Daihatsu: ["Applause", "Atrai", "Boon", "Copen", "Extol", "Fourtrak", "Gran Move", "Hijet", "Midget", "Mira", "Move", "Sportrak", "Tanto", "Trevis", "YRV"],
    DeLorean: ["Alpha5"],
    DFSK: ["C31", "C35", "EC35", "Fengon 5", "Fengon 7", "Glory 560", "Glory ix5", "Glory ix7", "K01", "K05"],
    Dodge: ["Avenger", "Caravan", "Charger Daytona", "Coronet", "Dart", "Grand Caravan", "Hornet", "Intrepid", "Magnum", "Monaco", "Neon", "Shadow", "Spirit", "Stealth", "Stratus", "Super Bee"],
    Dongfeng: ["Forthing T5 EVO", "Huge", "Mage", "Nammi 01", "Rich 6", "Voyah Courage", "Voyah Dream", "Voyah Passion"],
    DR: ["DR 1.0", "DR 2.0", "DR 3.0", "DR 7.0"],
    "DS Automobiles": ["DS 3 Cabrio", "DS 5", "DS 5LS", "DS 6", "DS N°4"],
    EBRO: ["S900"],
    Ferrari: ["156 F1", "208", "250 GT", "275 GTB", "312", "330 GTC", "365 GTB/4 Daytona", "456", "512 BB", "512 TR", "849 Testarossa", "Amalfi", "F355", "F512 M", "F80", "Monza SP1", "Monza SP2"],
    Fiat: ["500 Topolino", "600 Multipla", "1100", "1200", "1300", "1400", "1500", "1800", "2300", "128", "133", "147", "238", "242", "508 Balilla", "Albea", "Argo", "Brava", "Cronos", "Elba", "Fastback", "Linea", "Marengo", "Oggi", "Panorama", "Perla", "Petra", "Premio", "Pulse", "Siena", "Spazio", "Strada", "Titano"],
    Ford: ["Aerostar", "B-Max", "Bronco Sport", "Consul", "Contour", "Corsair", "Cortina", "Courier", "Crown Victoria", "Escape", "Everest", "Expedition", "Fairlane", "Falcon", "Figo", "Flex", "Freestar", "Fusion", "Galaxie", "Grand C-Max", "GT40", "Ikon", "Ka+", "Model A", "Model T", "Orion", "Pinto", "Popular", "Prefect", "StreetKa", "Taurus", "Territory", "Thunderbird", "Torino", "Windstar", "Zephyr", "Zodiac"],
    Genesis: ["G80 Electrified", "GV70 Electrified"],
    GMC: ["Envoy", "Jimmy", "Safari", "Savana", "Sonoma", "Syclone", "Terrain", "Typhoon", "Vandura"],
    GWM: ["Cannon", "Haval H2", "Haval H6", "Haval H9", "Haval Jolion", "Ora 03", "Ora 07", "Poer", "Tank 300", "Tank 500", "Wingle"],
    Honda: ["Acty", "Amaze", "Ascot", "Ballade", "BR-V", "Capa", "Concerto", "Crosstour", "e:N1", "Freed", "Inspire", "Life", "Logo", "Mobilio", "N360", "Prologue", "Quint", "Ridgeline", "S800", "Shuttle", "StepWgn", "Today", "Vigor", "WR-V", "Z"],
    Hummer: ["H3T"],
    Hyundai: ["Alcazar", "Aura", "Azera", "Casper", "Creta", "Eon", "Equus", "Genesis Coupe", "Grandeur", "H350", "i800", "ix55", "Lantra", "Porter", "Santa Cruz", "Santamo", "Scoupe", "Solaris", "Starex", "Tiburon", "Trajet", "Venue", "Verna", "XG30"],
    Infiniti: ["EX30", "EX35", "EX37", "I30", "I35", "J30", "JX35", "M30", "M37", "M45", "M56", "Q45", "Q70", "QX4", "QX56"],
    Innocenti: ["950 Spider", "A40", "C", "IM3", "J4", "J5", "Koral", "Mini De Tomaso", "Regent", "Small"],
    Isuzu: ["Amigo", "Ascender", "Aska", "Axiom", "Bighorn", "Campo", "Elf", "Gemini", "Impulse", "Midi", "MU-X", "Panther", "Piazza", "Rodeo", "Wizard"],
    Iveco: ["Crossway", "EuroStar", "Eurotech", "EuroTrakker", "Powerstar", "S-Way", "T-Way", "Trakker", "TurboDaily", "TurboStar", "X-Way", "Zeta"],
    Jaecoo: ["Jaecoo 5", "Jaecoo 6", "Jaecoo 8"],
    Jaguar: ["240", "340", "420", "Mark 1", "Mark V", "Mark VII", "Mark X", "Sovereign", "XJ6", "XJ12", "XJR-15", "XK120", "XK140", "XK150", "XK8"],
    Jeep: ["Comanche", "Commando", "DJ", "FC-150", "FC-170", "J10", "J20", "Jeepster", "M38", "Recon", "Scrambler", "Wagoneer S"],
    Kia: ["Amanti", "Besta", "Bongo", "Cadenza", "Clarus", "EV2", "Forte", "K5", "K7", "K8", "K9", "Opirus", "Quoris", "Ray", "Retona", "Rondo", "Seltos", "Sephia", "Syros", "Tasman", "Telluride"],
    Lada: ["110", "111", "112", "2101", "2105", "2106", "2107", "2108", "2109", "Aura", "Iskra", "Largus", "Niva Legend", "Niva Travel", "Oka", "XRAY"],
    Lamborghini: ["Centenario", "Countach LPI 800-4", "Essenza SCV12", "Fenomeno", "Jarama", "Reventón", "Sesto Elemento", "Sián", "Veneno"],
    Lancia: ["Aprilia", "Artena", "Astura", "Delta S4", "Dikappa", "Dilambda", "Epsilon", "Hyena", "Lambda", "LC2", "Theta", "Trikappa", "Zeta"],
    "Land Rover": ["101 Forward Control", "Defender 90", "Defender 110", "Defender 130", "Lightweight", "Series IIA", "Wolf"],
    Leapmotor: ["B10", "C01", "C11", "C16"],
    Lexus: ["IS F", "LM", "RC", "RC F", "TX"],
    Ligier: ["Ambra", "Be Sun", "Be Up", "Flex", "IXO", "JS RC", "JS2", "Myli", "Nova", "Optima", "X-Too"],
    Lotus: ["2-Eleven", "3-Eleven", "340R", "Carlton", "Cortina", "Eclat", "Elite", "Europa", "Evija", "Excel", "Seven", "Type 49", "Type 72"],
    "Lynk & Co": ["05", "07", "09", "900", "Z10"],
    Mahindra: ["Alturas G4", "BE 6", "Bolero", "Jeeto", "Marazzo", "Pik Up", "Quanto", "Roxor", "TUV300", "Verito", "XEV 9e", "Xylo", "XUV300", "XUV400", "XUV700"],
    Maserati: ["228", "250F", "3500 GT", "420", "430", "5000 GT", "A6", "Barchetta", "Coupé", "GranSport", "GT2 Stradale", "Kyalami", "Mexico", "Mistral", "Royale", "Sebring", "Tipo 61 Birdcage"],
    Maxus: ["D90", "Deliver 9", "eDeliver 7", "eTerron 9", "Euniq 5", "Euniq 6", "G10", "Mifa 9", "T60", "V80"],
    Mazda: ["818", "929", "Atenza", "Axela", "B-Series", "Bongo", "BT-50", "Capella", "Carol", "Cosmo", "CX-50", "CX-7", "CX-70", "CX-9", "CX-90", "Demio", "Familia", "Luce", "Mazda5", "Millenia", "Premacy", "Protegé", "R360", "RX-2", "RX-4", "RX-5", "Savanna"],
    "Mercedes-Benz": ["170", "220", "280 SE", "300 SEL", "540K", "600 Grosser", "Actros", "AMG GT 4-Door", "AMG ONE", "Arocs", "Atego", "Axor", "CLK GTR", "EQG", "MB100", "SLR McLaren", "SLS AMG", "SSK", "T1", "T2", "Vario", "W123", "W124", "W126", "W140"],
    MG: ["IM5", "IM6", "M9", "Maestro", "Magnette", "MG6", "MG7", "MGA", "MGB", "MGB GT", "MGF", "Midget", "Montego", "QS", "RV8", "TA", "TC", "TD"],
    Mini: ["1275 GT", "Clubvan", "Mini Pickup", "Mini Van", "One", "Traveller"],
    Mitsubishi: ["Airtrek", "Attrage", "Cordia", "Debonair", "Delica", "Diamante", "Dion", "Endeavor", "Galant", "Legnum", "Minica", "Montero", "Pajero iO", "RVR", "Shogun", "Space Gear", "Space Runner", "Space Wagon", "Tredia", "Triton", "Xforce", "Xpander"],
    Nissan: ["100NX", "240Z", "260Z", "280ZX", "300ZX", "Altima", "Armada", "Be-1", "Bluebird", "Cedric", "Cherry", "Elgrand", "Fairlady Z", "Frontier", "Fuga", "Gloria", "Kicks", "Kubistar", "Magnite", "March", "NV200", "NV300", "NV400", "Pao", "Prairie", "President", "Primastar", "Quest", "Rasheen", "Rogue", "S-Cargo", "Sentra", "Serena", "Stagea", "Stanza", "Sylphy", "Teana", "Terra", "Tiida", "Titan", "Versa", "Xterra", "Z"],
    NIO: ["EC6", "EC7", "EL8", "ES6", "ES7", "ES8", "ET5 Touring", "ET9", "Firefly", "ONVO L60"],
    Omoda: ["Omoda 7", "Omoda 9", "Omoda E5"],
    Opel: ["Admiral", "Ampera", "Ampera-e", "Arena", "Blitz", "Cascada", "Diplomat", "Kapitän", "Manta", "Olympia", "P4", "Rekord", "Speedster", "Super 6", "Vita"],
    Peugeot: ["202", "203", "204", "205 T16", "304", "305", "403", "405", "405 T16", "9X8", "908", "Boxer", "e-208", "e-2008", "iOn", "J5", "J7", "J9", "Landtrek"],
    Polestar: ["Polestar 5"],
    Pontiac: ["6000", "Aztek", "Bonneville", "Catalina", "G5", "G6", "G8", "Grand Prix", "Le Mans", "Montana", "Parisienne", "Phoenix", "Solstice", "Star Chief", "Sunbird", "Tempest", "Torrent", "Trans Am", "Trans Sport", "Ventura", "Vibe"],
    Porsche: ["356 Speedster", "804", "908", "917", "919 Hybrid", "930", "936", "956", "962", "964", "991", "992", "993", "996", "997", "RS Spyder"],
    RAM: ["1500 REV", "4500", "5500", "ProMaster City", "Rampage"],
    Renault: ["4 E-Tech", "4CV", "5 Turbo", "5 Turbo 3E", "6", "8", "9", "10", "12", "15", "16", "17", "Caravelle", "Dauphine", "Express", "Floride", "Fluence", "Frégate", "Grand Espace", "Juvaquatre", "Latitude", "Mascott", "Nevada", "Ondine"],
    "Rolls Royce": ["20/25", "25/30", "Boat Tail", "Silver Dawn", "Silver Ghost", "Silver Seraph", "Silver Spur", "Silver Wraith", "Sweptail"],
    Rover: ["100", "111", "114", "213", "216", "220", "416", "420", "620", "623", "820", "825", "827", "CityRover", "P2", "P3", "P4", "P5", "P5B", "Streetwise", "Vitesse"],
    Saab: ["9-3X", "92", "93", "95", "96", "99", "Sonett"],
    Seat: ["124", "132", "133", "1200 Sport", "1400", "1500", "Arosa", "Bocanegra", "Formula", "Fura", "Salsa", "Tango", "Terra", "Trans"],
    Seres: ["7"],
    Škoda: ["100", "110", "110 R", "1101 Tudor", "130 RS", "1201", "440", "445", "450", "Epiq", "Estelle", "Garde", "Kylaq", "Popular", "Praktik"],
    Smart: ["#5"],
    SsangYong: ["Actyon Sports", "Chairman", "Istana", "Kallista", "Korando Family", "Korando Sports", "Kyron", "Rexton Sports", "Stavic"],
    Subaru: ["Chiffon", "Crosstrek", "Dex", "Domingo", "Exiga", "Leone", "Libero", "Loyale", "Pleo", "R1", "R2", "Rex", "Sambar", "Stella", "Traviq", "Trezia"],
    Suzuki: ["Aerio", "Brezza", "Cara", "Carry", "Cervo", "Ciaz", "Dzire", "Equator", "Ertiga", "Escudo", "Every", "Forenza", "Fronx", "Hustler", "Kei", "Lapin", "LJ80", "Reno", "Sidekick", "SJ410", "SJ413", "Spacia", "Splash", "Verona", "XL7"],
    Tata: ["Ace", "Altroz", "Aria", "Bolt", "Curvv", "Estate", "Harrier", "Hexa", "Indigo", "Magic", "Manza", "Nexon", "Punch", "Sierra", "Sumo", "Telcoline", "Tiago", "Tigor", "Vista", "Winger", "Yodha", "Zest"],
    Tesla: ["Cybercab"],
    Toyota: ["2000GT", "4Runner", "Altezza", "Aristo", "Avalon", "Avensis Verso", "Caldina", "Chaser", "Coaster", "Corolla Verso", "Corona", "Cresta", "Dyna", "Echo", "FJ Cruiser", "Hiace", "Hilux Surf", "Mark II", "Matrix", "MegaCruiser", "Mirai", "Passo", "Picnic", "Porte", "Publica", "Ractis", "Rush", "Sequoia", "Sienna", "Soarer", "Solara", "Sports 800", "Sprinter Trueno", "Stout", "Tacoma", "Tundra", "Venza", "Verso-S", "Vitz", "Yaris Verso"],
    Volkswagen: ["181", "Bora", "CC", "California", "Caravelle", "Crafter", "Cross Golf", "CrossPolo", "e-Golf", "e-Up!", "Gol", "Golf Plus", "ID.6", "Karmann Ghia", "Kombi", "Nivus", "Parati", "Routan", "Saveiro", "Taos", "Transporter", "Type 2", "Type 3", "Type 4", "Voyage"],
    Volvo: ["66", "120", "164", "244", "245", "262C", "340", "360", "440", "780", "C303", "Duett", "EM90", "Laplander", "P1900", "PV444", "PV544", "S70"],
    XPeng: ["G3", "G3i", "G7", "Mona M03", "P5", "P7+", "X9"],
    Zeekr: ["007", "009", "Mix"],

    // ---------- Marchi mancanti: nuove entrate ----------
    Aiways: ["U5", "U6"],
    Avatr: ["06", "07", "11", "12"],
    "Automobili Pininfarina": ["B95", "Battista"],
    Changan: ["Alsvin", "CS35", "CS55", "CS75", "CS85", "Deepal L07", "Deepal S07", "Eado", "Hunter", "UNI-K", "UNI-T", "UNI-V"],
    Chery: ["Arrizo 5", "Arrizo 8", "eQ1", "Fulwin", "QQ", "Tiggo 2", "Tiggo 3", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Tiggo 9"],
    Czinger: ["21C"],
    Denza: ["D9", "N7", "N8", "Z9", "Z9 GT"],
    Fisker: ["Karma", "Ocean"],
    Geely: ["Atlas", "Coolray", "Emgrand", "EX5", "Galaxy E5", "Galaxy E8", "Geometry C", "Monjaro", "Okavango", "Panda Mini", "Starray", "Tugella", "Xingyue L"],
    Hongqi: ["CA72", "E-HS9", "EH7", "EHS7", "H5", "H9", "HS5", "HS7"],
    JAC: ["e-JS4", "e-S4", "iEV7S", "J7", "Refine", "S3", "S4", "T8"],
    Kimera: ["EVO37", "EVO38"],
    Koenigsegg: ["Agera", "Agera R", "Agera RS", "CC850", "CC8S", "CCR", "CCX", "Gemera", "Jesko", "One:1", "Regera"],
    Lucid: ["Air", "Gravity"],
    Microlino: ["Microlino", "Microlino Lite"],
    Rimac: ["Concept One", "Nevera"],
    Rivian: ["EDV", "R1S", "R1T", "R2", "R3"],
    Roewe: ["350", "550", "750", "D7", "i5", "i6", "iMAX8", "Marvel X", "RX5", "RX8"],
    Skywell: ["BE11", "ET5", "HT-i"],
    Togg: ["T10F", "T10X"],
    VinFast: ["Fadil", "Lux A2.0", "Lux SA2.0", "President", "VF 3", "VF 5", "VF 6", "VF 7", "VF 8", "VF 9"],
    Xiaomi: ["SU7", "SU7 Ultra", "YU7"],
    Zenvo: ["Aurora", "ST1", "TS1", "TSR", "TSR-S"],

    // ---------- Marchi mancanti: sportive, hypercar, artigianali ----------
    AC: ["3000ME", "428", "Ace", "Aceca", "Cobra"],
    Acura: ["ADX", "CL", "CSX", "EL", "ILX", "Integra", "Legend", "MDX", "NSX", "RDX", "RL", "RLX", "RSX", "SLX", "TL", "TLX", "TSX", "Vigor", "ZDX"],
    Alpina: ["B3", "B4", "B5", "B6", "B7", "B8", "B10", "B12", "D3", "D4", "D5", "Roadster V8", "XB7", "XD3", "XD4"],
    Apollo: ["Apollo IE", "Gumpert Apollo"],
    Ariel: ["Atom", "Hipercar", "Nomad"],
    ATS: ["2500 GT"],
    BAC: ["Mono", "Mono R"],
    Bizzarrini: ["5300 GT Strada", "Europa 1900", "Giotto", "P538"],
    Bremach: ["Brio", "T-Rex"],
    Bugatti: ["Bolide", "Centodieci", "Chiron", "Divo", "EB110", "La Voiture Noire", "Mistral", "Tourbillon", "Type 13", "Type 35", "Type 41 Royale", "Type 57", "Veyron"],
    Caterham: ["21", "CSR", "Seven", "Seven 170", "Seven 360", "Seven 420", "Seven 620"],
    Cisitalia: ["202", "D46"],
    Dallara: ["Stradale"],
    "De Tomaso": ["Bigua", "Deauville", "Guarà", "Longchamp", "Mangusta", "P72", "Pantera", "Vallelunga"],
    Donkervoort: ["D8", "D8 GTO", "F22", "S8"],
    Ginetta: ["Akula", "G4", "G15", "G40", "G50", "G55"],
    Hennessey: ["Venom F5", "Venom GT"],
    "Hispano-Suiza": ["Alfonso XIII", "Carmen", "H6", "J12"],
    Iso: ["Fidia", "Grifo", "Isetta", "Lele", "Rivolta IR 300"],
    Jensen: ["541", "CV8", "FF", "Healey", "Interceptor"],
    Lister: ["Knobbly", "Storm"],
    Marcos: ["LM500", "Mantis", "Mantula"],
    Mazzanti: ["Evantra"],
    Morgan: ["3 Wheeler", "4/4", "Aero 8", "Aero Coupé", "Plus 4", "Plus 8", "Plus Four", "Plus Six", "Roadster", "Super 3"],
    Noble: ["M12", "M400", "M500", "M600"],
    OSCA: ["1600 GT", "MT4"],
    Pagani: ["Huayra", "Huayra BC", "Huayra R", "Imola", "Utopia", "Zonda", "Zonda Codalunga", "Zonda R"],
    Radical: ["RXC", "SR1", "SR3", "SR8", "SR10"],
    Ruf: ["BTR", "CTR", "CTR2", "CTR3", "Rodeo", "RT 12", "SCR"],
    Shelby: ["Cobra", "GT350", "GT500", "Series 1"],
    Siata: ["208S", "Amica", "Spring"],
    Spyker: ["B6 Venator", "C8", "C8 Aileron", "C12", "D8"],
    SSC: ["Tuatara", "Ultimate Aero"],
    TVR: ["3000S", "Cerbera", "Chimaera", "Grantura", "Griffith", "S-Series", "Sagaris", "T350", "Tamora", "Tuscan", "Vixen"],
    Venturi: ["260", "400 GT", "America", "Atlantique", "Fétish"],
    "W Motors": ["Fenyr SuperSport", "Lykan HyperSport"],
    Wiesmann: ["GT", "MF3", "MF4", "MF5", "Project Thunderball", "Roadster"],

    // ---------- Marchi mancanti: vecchie glorie ----------
    AMC: ["AMX", "Concord", "Eagle", "Gremlin", "Hornet", "Javelin", "Matador", "Pacer", "Rambler", "Spirit"],
    Aro: ["10", "24", "240", "243", "244", "M461", "Spartana"],
    Austin: ["1100", "1300", "A30", "A35", "A40", "A60 Cambridge", "Allegro", "Maestro", "Maxi", "Metro", "Mini", "Montego", "Princess"],
    "Austin-Healey": ["100", "100-6", "3000", "Sprite"],
    "Auto Union": ["1000", "1000 SP", "Type A", "Type B", "Type C", "Type D"],
    Borgward: ["Arabella", "BX5", "BX7", "Hansa", "Isabella", "P100"],
    Buick: ["Cascada", "Century", "Electra", "Enclave", "Encore", "Envision", "Envista", "Grand National", "LaCrosse", "LeSabre", "Lucerne", "Park Avenue", "Rainier", "Regal", "Rendezvous", "Riviera", "Roadmaster", "Skylark", "Terraza", "Verano"],
    Daimler: ["DS420", "Double Six", "Majestic", "SP250", "Sovereign", "Super Eight", "V8 250"],
    Datsun: ["120Y", "1200", "240Z", "260Z", "280Z", "280ZX", "510", "Bluebird", "Cherry", "Fairlady", "GO", "GO+", "mi-DO", "on-DO", "redi-GO", "Stanza", "Sunny", "Violet"],
    DKW: ["3=6", "F1", "F5", "F7", "F8", "F89", "F91", "F93", "Junior", "Monza", "Munga"],
    "Facel Vega": ["Excellence", "Facel 6", "Facel II", "Facellia", "FV", "HK500"],
    FSO: ["125p", "Polonez", "Syrena", "Warszawa"],
    GAZ: ["24", "3110", "31105", "69", "Chaika", "Gazelle", "Pobeda", "Sobol", "Tigr", "Volga"],
    Giannini: ["590", "650"],
    Hillman: ["Avenger", "Hunter", "Imp", "Minx"],
    Hindustan: ["Ambassador", "Contessa", "Landmaster"],
    Horch: ["830", "853", "930"],
    Lincoln: ["Aviator", "Blackwood", "Continental", "Corsair", "LS", "Mark VIII", "MKC", "MKS", "MKT", "MKX", "MKZ", "Nautilus", "Navigator", "Town Car", "Zephyr"],
    Matra: ["530", "Bagheera", "Djet", "Murena", "Rancho"],
    Maybach: ["57", "62", "Exelero", "Zeppelin"],
    Mercury: ["Capri", "Comet", "Cougar", "Grand Marquis", "Marauder", "Mariner", "Milan", "Monterey", "Mountaineer", "Mystique", "Sable", "Topaz", "Tracer", "Villager"],
    Moretti: ["500", "600", "750", "850"],
    Morris: ["1100", "Ital", "Marina", "Mini", "Minor", "Oxford"],
    Moskvich: ["3", "400", "401", "402", "403", "407", "408", "412", "2140", "2141 Aleko"],
    NSU: ["1000", "1200", "Prinz", "Ro 80", "Sport Prinz", "TT", "Wankel Spider"],
    Oldsmobile: ["442", "88", "98", "Achieva", "Alero", "Aurora", "Bravada", "Cutlass", "Delta 88", "Intrigue", "Silhouette", "Starfire", "Toronado"],
    Packard: ["Caribbean", "Clipper", "Hawk", "One-Twenty", "Patrician", "Super Eight", "Twin Six"],
    Panhard: ["24", "CD", "Dyna X", "Dyna Z", "PL 17"],
    Perodua: ["Alza", "Aruz", "Ativa", "Axia", "Bezza", "Kancil", "Kelisa", "Kembara", "Kenari", "Myvi", "Viva"],
    Plymouth: ["Barracuda", "Belvedere", "Breeze", "Duster", "Fury", "GTX", "Horizon", "Neon", "Prowler", "Reliant", "Road Runner", "Satellite", "Superbird", "Valiant", "Volaré", "Voyager"],
    "Polski Fiat": ["125p", "126p"],
    Proton: ["Arena", "Exora", "Gen-2", "Iriz", "Juara", "Perdana", "Persona", "Preve", "Putra", "Saga", "Satria", "Savvy", "Waja", "Wira", "X50", "X70", "X90"],
    Reliant: ["Kitten", "Regal", "Robin", "Scimitar"],
    Riley: ["Elf", "Kestrel", "One-Point-Five"],
    Saturn: ["Astra", "Aura", "Ion", "L-Series", "Outlook", "Relay", "S-Series", "Sky", "Vue"],
    Scion: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
    Simca: ["1000", "1100", "1300", "1301", "1307", "1500", "1501", "Ariane", "Aronde", "Chambord", "Vedette"],
    Studebaker: ["Avanti", "Champion", "Commander", "Golden Hawk", "Hawk", "Lark", "President", "Starliner"],
    Sunbeam: ["Alpine", "Imp", "Rapier", "Tiger"],
    Talbot: ["Alpine", "Horizon", "Murena", "Samba", "Solara", "Sunbeam", "Tagora"],
    Tatra: ["57", "87", "600 Tatraplan", "603", "613", "700", "T815"],
    Trabant: ["1.1", "601", "P50", "P60"],
    Triumph: ["2000", "Acclaim", "Dolomite", "GT6", "Herald", "Spitfire", "Stag", "Toledo", "TR2", "TR3", "TR4", "TR5", "TR6", "TR7", "TR8", "Vitesse"],
    UAZ: ["452 Buhanka", "469", "Hunter", "Patriot", "Pickup", "Profi"],
    Vauxhall: ["Adam", "Agila", "Antara", "Astra", "Belmont", "Calibra", "Carlton", "Cavalier", "Chevette", "Combo", "Corsa", "Cresta", "Crossland", "Firenza", "Frontera", "Grandland", "Insignia", "Magnum", "Meriva", "Mokka", "Monaro", "Movano", "Nova", "Omega", "Senator", "Signum", "Tigra", "Vectra", "Victor", "Viva", "Vivaro", "VXR8", "Zafira"],
    Wanderer: ["W23", "W24", "W25K", "W50"],
    Wartburg: ["1.3", "311", "312", "313", "353"],
    Zastava: ["10", "101", "128 Skala", "750", "Florida", "Koral", "Yugo 45", "Yugo GV", "Yugo Tempo"],
    ZAZ: ["965", "966", "968", "Forza", "Lanos", "Sens", "Slavuta", "Tavria", "Vida"],

    // ---------- Marchi mancanti: microcar e quadricicli ----------
    Bellier: ["Divane", "Jade", "Opale"],
    Estrima: ["Birò"],
    Grecav: ["Eke", "Sonique"],
    Italcar: ["Attiva C2", "Attiva C3", "Attiva C4"],
    JDM: ["Abaca", "Aloes", "Roxsy", "Titane", "Xheos"],
    Tazzari: ["Zero", "Zero City", "Zero EM1"],

    // ---------- Marchi mancanti: nuovi produttori cinesi e EV globali ----------
    Aion: ["ES", "Hyper GT", "S", "V", "Y Plus"],
    Baojun: ["510", "530", "730", "Kiwi EV", "Yep"],
    "Faraday Future": ["FF 91"],
    Haval: ["Dargo", "F7", "H6", "H9", "Jolion"],
    HiPhi: ["X", "Y", "Z"],
    "IM Motors": ["L6", "LS6", "LS7"],
    "Isotta Fraschini": ["Tifosi"],
    Karma: ["GS-6", "Revero"],
    "Li Auto": ["L6", "L7", "L8", "L9", "Mega"],
    Neta: ["Neta L", "Neta S", "Neta U", "Neta V", "Neta X"],
    "Rising Auto": ["F7", "R7"],
    Tank: ["300", "500", "700"],
    Voyah: ["Courage", "Dreamer", "Free", "Passion"],
    WEY: ["Coffee 01", "Coffee 02", "VV7"],
    Wuling: ["Air EV", "Bingo", "Hongguang Mini EV", "Victory"],
  },

  moto: {
    // ---------- Marchi gia' presenti: ampliamento gamma ----------
    Aprilia: ["Atlantic", "Caponord 1200", "ETV 1000 Caponord", "Habana", "Leonardo", "Mana 850", "Mojito", "Moto 6.5", "RS 250", "RS 50", "RS4 125", "RSV 1000 R", "RX 125", "RXV 450", "Shiver 750", "SL 750", "SR 50", "SR Motard", "Sportcity", "SX 125", "SXV 450", "Tuareg 600 Wind", "Tuono 125"],
    Benelli: ["750 Sei", "900 Sei", "BKX 300", "BN 125", "BN 302", "Leoncino 250", "Leoncino 800", "Pepe", "TNT 899", "TNT 1130", "Tornado 900 Tre", "TRE-K", "TRK 251", "TRK 552", "Velvet", "Zafferano"],
    Beta: ["Alp 4.0", "Ark", "Eikon", "Evo", "Motard 2T", "RR 125", "RR 200", "RR 390", "RR 430", "RR 480", "RR 50", "Tempo"],
    Bimota: ["BB1", "DB1", "DB2", "DB5", "DB7", "DB11", "KB1", "KB2", "KB3", "Mantra", "SB2", "SB6", "SB8K", "Tesi 1D", "Tesi 2D", "Tesi 3D", "Vdue", "YB4", "YB5", "YB11"],
    BMW: ["C 600 Sport", "C 650 GT", "C1", "CE 02", "F 650 CS", "F 650 GS", "F 700 GS", "F 800 R", "F 800 ST", "F 900 XR", "G 310 GS", "G 650 X", "HP2", "HP4", "K 1", "K 75", "K 1200 RS", "K 1300 R", "K 1300 S", "K 1600 B", "K 1600 GTL", "M 1000 R", "M 1000 RR", "M 1000 XR", "R 100 GS", "R 100 RS", "R 1100 GS", "R 1100 S", "R 1150 GS", "R 1200 GS", "R 1200 RT", "R 1200 S", "R 1250 RT", "R 1300 RT", "R 12", "R 12 nineT", "R 18 B", "R 32", "R 60", "R 69 S", "R 75", "R nineT Scrambler"],
    "Can-Am": ["Ryker", "Spyder F3", "Spyder RT"],
    CFMoto: ["125NK", "1250TR-G", "450CL-C", "450NK", "450SR", "450SS", "650MT", "650NK", "675SR-R", "700MT", "800MT", "800NK", "Papio"],
    Ducati: ["1098", "1198", "1199 Panigale", "1299 Panigale", "750 SS", "848", "888", "899 Panigale", "900 SS", "959 Panigale", "DesertX Rally", "Diavel V4", "GT1000", "Hypermotard 698 Mono", "Hypermotard 950", "Mach 1", "Mike Hailwood Replica", "Monster 1200", "Monster 797", "Monster 821", "Monster 900", "Multistrada 1000DS", "Pantah", "Paso", "Paul Smart 1000", "Scrambler 1100", "Scrambler Icon", "ST2", "ST3", "ST4", "Streetfighter V2", "Superleggera V4"],
    Fantic: ["Caballero 125", "Caballero 500", "Caballero 700", "Imola", "Issimo", "Stealth", "XE 125", "XEF 250", "XEF 450", "XXF"],
    Gilera: ["150 Rossa", "Coguar", "CX 125", "Eaglet", "Ice", "KZ 125", "Nordwest 600", "RC 600", "RCR", "SMT", "SP01", "Stalker", "Typhoon"],
    "Harley-Davidson": ["1200 Custom", "CVO Street Glide", "Deluxe", "Duo-Glide", "Dyna", "Fat Bob", "Flathead", "Forty-Eight", "Freewheeler", "Heritage Classic", "Hydra-Glide", "Iron 1200", "Low Rider", "Panhead", "Seventy-Two", "Softail Slim", "Sport Glide", "Sportster S", "Street 750", "Street Glide", "Street Rod", "Super Glide", "Tri Glide", "Ultra Limited", "Wide Glide", "WL", "X350", "X500", "XR1200", "XR750"],
    Honda: ["@125", "CB1000 Hornet", "CB1100", "CB125F", "CB125R", "CB1300", "CB300R", "CB400F", "CB500 Hornet", "CB750 Four", "CB900F", "CBR1000RR", "CBR125R", "CBR250R", "CBR300R", "CBR500R", "CBR600F", "CBR900RR Fireblade", "CBX550", "CRF250L", "CRF300L", "CRF450L", "CT125 Hunter Cub", "CX500", "Dax", "Deauville", "Dio", "Dominator NX650", "EM1 e:", "Firestorm", "Forza 125", "Forza 350", "Forza 750", "Fury", "Grom", "Integra 750", "NC750S", "NR750", "NS400R", "NSR125", "NSR250", "NT700V", "Pan-European", "PCX 125", "RC213V-S", "Rune", "RVF400", "SH300", "Shadow", "Silver Wing", "Super Cub", "Varadero", "VF750", "VFR1200F", "VFR1200X Crosstourer", "VT750", "VTR1000 SP-1", "VTX1800", "XL600", "XR650R", "Zoomer"],
    Husqvarna: ["250 WR", "701 Supermoto", "CR 125", "FC 450", "FE 250", "FE 350", "FE 450", "FE 501", "Nuda 900", "SM 610", "Svartpilen 125", "Svartpilen 701", "TC 250", "TE 150", "TE 250", "TE 300", "TE 610", "TR650 Strada", "TR650 Terra", "Vitpilen 125", "Vitpilen 701"],
    "Indian Motorcycle": ["101 Scout", "Challenger", "Chief Bobber", "Chief Dark Horse", "Four", "Powerplus", "Pursuit", "Roadmaster", "Scout Bobber", "Scout Rogue", "Sport Chief", "Super Chief"],
    Italjet: ["Formula", "Grifon", "Jet Set", "Millennium", "Roma", "Torpedo", "Velocifero"],
    Kawasaki: ["1400GTR", "750 H2 Mach IV", "900 Z1", "ER-5", "ER-6f", "ER-6n", "Estrella", "GPZ500S", "KLE500", "KLX230", "KLX300", "KX250", "KX450", "Mach III H1", "Ninja 1000SX", "Ninja 125", "Ninja 500", "Ninja e-1", "Ninja H2 SX", "Ninja H2R", "Versys 1100", "Vulcan 1700", "Vulcan 900", "W175", "W650", "Z e-1", "Z H2", "Z1000", "Z1000SX", "Z125", "Z300", "Z500", "Z650RS", "Z750", "Z800", "Z900RS", "ZX-12R", "ZX-4RR", "ZX-7R", "ZX-9R", "ZZR1100", "ZZR600"],
    Keeway: ["Hurricane", "K-Light 125", "Logik", "RKF 125", "RY6", "Superlight", "TX 125", "V302C", "Vieste"],
    KTM: ["1050 Adventure", "1090 Adventure", "1190 Adventure", "1190 RC8", "1290 Super Duke GT", "1390 Super Adventure", "1390 Super Duke R", "125 SX", "150 EXC", "250 EXC", "250 EXC-F", "250 SX-F", "300 EXC", "350 EXC-F", "350 SX-F", "390 Enduro R", "390 SMC R", "450 EXC-F", "450 SX-F", "50 SX", "65 SX", "690 SMC R", "790 Adventure", "85 SX", "890 Duke R", "890 SMT", "950 Adventure", "950 Super Enduro", "990 Adventure", "990 RC R", "990 SM", "990 SMT", "990 Super Duke", "Freeride 250 F", "Freeride E-XC", "RC 125", "RC 8C"],
    Kymco: ["AK 550", "CV3", "Dink", "Downtown", "DTX 360", "Grand Dink", "Heroism", "Hipster", "K-Pipe", "Like", "Movie", "Pulsar", "Quannon", "Sento", "Super Dink", "Venox", "Vitality", "Xciting", "Yager", "Zing"],
    Malaguti: ["Ciak", "Drakon", "Dune", "F12 Phantom", "F15 Firefox", "Monte Pro", "Password", "Spidermax", "XSM", "XTM"],
    "Moto Guzzi": ["1000 SP", "850 T", "850 T3", "Airone", "Alce", "Astore", "Audace", "Bellagio", "Breva", "Cardellino", "Centauro", "Condor", "Daytona 1000", "Eldorado", "Ercole", "Ercolino", "Florida", "Galletto", "GTS", "Lodola", "MGX-21", "Mille GT", "Nevada", "Otto Cilindri", "Quota", "Sport 1100", "Stornello", "V11 Sport", "V35", "V50", "V65", "V7 Special", "V7 Sport", "Zigolo"],
    "MV Agusta": ["125 TR", "350 B", "350 Ipotesi", "500 Tre", "600 4C", "750 S America", "800 Rivale", "Brutale 1000", "Brutale 675", "Brutale 800", "Enduro Veloce", "F3 675", "F3 800", "LXP Orioli", "Stradale 800"],
    Norton: ["16H", "961 Commando", "Atlas", "Atlas Nomad", "Atlas Ranger", "ES2", "F1", "International", "Interpol", "Jubilee", "Manx", "Manx R", "Model 18", "NRV588", "V4CR", "V4 SV"],
    "Peugeot Motocycles": ["101", "103", "104", "105", "Belville", "Buxy", "Citystar", "e-Streetzone", "Elystar", "Geopolis", "Jet Force", "Kisbee", "Ludix", "Metropolis", "PM-01", "Pulsion", "Satelis", "Streetzone", "Tweet", "Vivacity", "XP6", "Zenith"],
    Piaggio: ["Boxer", "Bravo", "Carnaby", "Ciao", "Fly", "Free", "Grillo", "Hexagon", "NRG", "Si", "Skipper", "Typhoon", "X7", "X8", "X9"],
    Rieju: ["Aventura", "Blast", "Century", "Marathon", "MR 300", "Nuuk", "RS2", "RS3", "SMX", "Tango"],
    "Royal Enfield": ["Bear 650", "Bullet 500", "Classic 500", "Classic 650", "Constellation", "Continental GT 535", "Flying Flea C6", "Goan Classic 350", "Guerrilla 450", "Scram 440", "Thunderbird 350", "Thunderbird 500"],
    Suzuki: ["Avenue", "B-King", "Boulevard M109R", "Burgman 400", "Burgman 650", "Burgman Street", "DR650", "DR800 Big", "GN125", "GS1000", "GS750", "GSF1200 Bandit", "GSF1250 Bandit", "GSR600", "GSR750", "GSX-R125", "GSX-S1000GT", "GSX-S125", "GSX1400", "GSX250R", "GT380", "GT550", "GT750", "Inazuma", "Intruder", "Marauder", "RF600R", "RF900R", "RGV250 Gamma", "RM-Z250", "RM-Z450", "RM250", "Savage LS650", "SV1000", "TL1000S", "TU250", "V-Strom 1000", "V-Strom 250", "V-Strom 800DE", "VanVan"],
    SWM: ["Ace of Spades", "Gran Milano", "Gran Turismo", "Hoku", "Outlaw", "RS 500 R", "Six Days", "SM 500 R", "Varez"],
    Sym: ["ADXTG", "Cruisym", "HD 300", "Husky", "Jet 14", "Jet X", "Maxsym", "Maxsym TL", "Mio", "NH X", "Orbit", "Symphony", "Wolf"],
    Triumph: ["Adventurer", "America", "Bonneville Bobber", "Bonneville Speedmaster", "Bonneville T100", "Daytona 600", "Daytona 660", "Daytona 955i", "Legend TT", "Scrambler 400 X", "Speed 400", "Speed Triple 1050", "Speed Triple RS", "Sprint GT", "Sprint ST", "Street Scrambler", "Street Triple RS", "Street Twin", "T140 Bonneville", "Thruxton RS", "Thunderbird", "Tiger 1050", "Tiger 660 Sport", "Tiger 850 Sport", "Tiger Explorer", "Tiger Sport", "TR6 Trophy", "Trident 750", "X-75 Hurricane"],
    Vespa: ["98", "125 Faro Basso", "Cosa", "ET2", "ET4", "GS 150", "GT", "GTS Super", "LX", "LXV", "PK 125", "PK 50", "Rally 180", "Rally 200", "S", "Sei Giorni", "SS 180", "T5"],
    Yamaha: ["BW's", "Cygnus", "D'elight", "Drag Star", "DT125", "DT50", "FZ1", "FZ6", "FZ750", "FZ8", "FZR600", "FZS1000 Fazer", "Jog", "Majesty", "MT-01", "MT-15", "Neo's", "R1M", "R9", "RD250", "RD400", "RD500LC", "Serow", "SR250", "SR400", "SR500", "TDM850", "TDM900", "TDR125", "Tracer 7", "Tracer 700", "TRX850", "TW200", "TZR125", "TZR250", "Virago", "WR125R", "WR450F", "Why", "XJ600 Diversion", "XJ900", "XJR1300", "XS1100", "XS650", "XSR125", "XSR700", "XSR900 GP", "XT1200Z Super Ténéré", "XT500", "XT660R", "XT660Z Ténéré", "XTZ750 Super Ténéré", "XV950 Bolt", "YA-1", "YZ125", "YZ250", "YZ250F", "YZ450F", "YZF-R15"],
    "Zero Motorcycles": ["DS", "DSR/X", "FX", "FXE", "FXS", "S", "SR", "SR/S"],

    // ---------- Marchi mancanti: nuove entrate ----------
    Bajaj: ["Avenger 220", "Boxer", "Chetak", "CT100", "Discover", "Dominar 400", "Platina", "Pulsar 150", "Pulsar N250", "Pulsar NS200", "Pulsar RS200"],
    Brixton: ["Cromwell 125", "Crossfire 125", "Crossfire 500", "Felsberg 125", "Glanville 250", "Sunray 125"],
    Energica: ["Ego", "EsseEsse9", "Eva", "Eva Ribelle", "Experia"],
    Hero: ["Glamour", "HF Deluxe", "Karizma", "Maestro", "Mavrick 440", "Passion", "Pleasure", "Splendor", "Xpulse 200", "Xtreme 160R"],
    Hyosung: ["Comet", "GD250N", "GT250", "GT650", "GV250", "GV650 Aquila", "RT125"],
    Kove: ["321R", "450 Rally", "800X"],
    LiveWire: ["One", "S2 Alpinista", "S2 Del Mar", "S2 Mulholland"],
    Macbor: ["Eight Mile", "Montana XR5", "Rockster"],
    Mash: ["Black Seven", "Five Hundred", "Scrambler 400", "Seventy"],
    NIU: ["MQi", "NQi", "RQi", "UQi"],
    "QJ Motor": ["SRK 125", "SRK 600", "SRK 700", "SRK 800", "SRT 550", "SRT 800", "SRV 550"],
    Silence: ["S01", "S02"],
    "Super Soco": ["CPx", "CUx", "TC", "TC Max", "TS", "Wanderer"],
    TVS: ["Apache RR 310", "Apache RTR 160", "iQube", "Jupiter", "Ntorq", "Raider 125", "Ronin", "Star City"],
    UM: ["DSR Adventure", "Renegade Commando", "Renegade Sport"],
    Voge: ["300 Rally", "300R", "500DS", "525DSX", "650DS", "900DSX", "SR4 Max"],
    Zontes: ["350R", "350T", "350X", "703F", "GK 350", "ZT 125 U"],

    // ---------- Marchi mancanti: italiani ed europei, fuoristrada e scooter ----------
    Aermacchi: ["Ala d'Oro", "Ala Verde", "Chimera"],
    Askoll: ["eS1", "eS2", "eS3", "NGS"],
    Cagiva: ["Alazzurra", "Aletta", "Elefant", "Freccia", "Gran Canyon", "Mito", "Navigator", "Planet", "Prima", "Raptor", "River", "Supercity", "V-Raptor", "W16"],
    Derbi: ["Atlantis", "Boulevard", "GPR 125", "GPR 50", "Mulhacén", "Mulhacén Café", "Senda", "Terra", "Variant"],
    "FB Mondial": ["Flat Track 125", "HPS 125", "HPS 300", "Piega 125", "SMX 125", "Sportclassic"],
    Garelli: ["Bimatic", "Ciclone", "Eureka", "Katia", "Noi", "Rekord", "Tiesse", "Vip"],
    GasGas: ["EC 250", "EC 300", "ES 700", "MC 250F", "MC 450F", "Pampera", "SM 700", "TXT Racing", "Wild HP"],
    Horex: ["Imperator", "Regina", "VR6"],
    Husaberg: ["FE 450", "FE 570", "TE 300"],
    Lambretta: ["D", "DL", "G350", "GP", "LD", "LI", "SX", "TV", "V125", "V200", "X300"],
    Laverda: ["1000 3C", "1200", "650 Sport", "668 Ghost", "750 Formula", "750 SF", "Jota", "Montjuic", "RGS", "Strike"],
    Montesa: ["Brio", "Cappra", "Cota 301RR", "Cota 4RT", "Enduro 360", "Impala"],
    "Moto Morini": ["3 ½", "Camel", "Corsaro", "Corsaro 1200", "Excalibur", "Granpasso", "Kanguro", "Scrambler 1200", "Seiemmezzo SCR", "Seiemmezzo STR", "Sport 1200", "X-Cape 650"],
    Motom: ["48", "Daina", "Zeffiro"],
    MZ: ["1000S", "Baghira", "ETZ 250", "ETZ 251", "Mastiff", "RT 125", "Skorpion", "TS 250"],
    Ossa: ["Explorer", "Phantom", "Stiletto", "TR280i"],
    Puch: ["Cobra", "Maxi", "Monza"],
    Scomadi: ["TL125", "TL50", "TT125", "TT300"],
    Sherco: ["SE 300", "SEF 450", "SM 125", "ST 300", "TY 125", "X-Ride"],
    Simson: ["Habicht", "S51", "Schwalbe", "SR50", "Star"],
    TGB: ["Blade"],
    "TM Racing": ["EN 300", "EN 450 Fi", "MX 250", "SMX 450"],
    Vyrus: ["984 C3 2V", "986 M2"],
    Zündapp: ["Bella", "GTS 50", "KS 601", "KS 750"],

    // ---------- Marchi mancanti: vecchie glorie ----------
    AJS: ["7R", "Model 18", "Porcupine"],
    "Brough Superior": ["Lawrence", "Pendine", "SS100", "SS80"],
    BSA: ["A10 Golden Flash", "Bantam", "Gold Star", "Lightning", "Rocket 3", "Spitfire", "Thunderbolt"],
    Buell: ["1125R", "Hammerhead 1190", "M2 Cyclone", "S1 Lightning", "Super Cruiser", "Ulysses", "XB12S Lightning", "XB9R Firebolt"],
    Bultaco: ["Astro", "Brinco", "Frontera", "Metralla", "Pursang", "Sherpa T"],
    Daelim: ["Daystar", "Otello", "Roadwin", "S2", "VL 125"],
    "Excelsior-Henderson": ["Super X"],
    Jawa: ["250", "350", "42", "42 Bobber", "500 OHC", "Perak"],
    Kreidler: ["Florett"],
    Maico: ["GS 400", "MC 250"],
    Matchless: ["G12", "G3", "G50", "G80"],
    Ural: ["cT", "Gear Up", "M72", "Patrol", "Solo", "Tourist"],
    Velocette: ["KTT", "LE", "Thruxton", "Venom", "Viper"],
    Victory: ["Cross Country", "Hammer", "Judge", "Kingpin", "Magnum", "Octane", "Vegas", "Vision"],
    Vincent: ["Black Lightning", "Black Prince", "Black Shadow", "Comet", "Rapide"],

    // ---------- Marchi mancanti: elettrico e mercati emergenti ----------
    "Ola Electric": ["S1", "S1 Air", "S1 Pro"],
    Yadea: ["C1S", "G5", "Kando 350S", "T9"],
  },
};
